export const Action_Types = {
    ADD_NEW_TODO: "ADD_NEW_TODO",
    THEME_CHANGE: "THEME_CHANGE",
    REMOVE_SELECTED_TODO: "REMOVE_SELECTED_TODO",
    STRIKE_HAS_CHECKED: "STRIKE_HAS_CHECKED",
    CLEAR_COMPLETED_TODO: "CLEAR_COMPLETED_TODO",
    COMPLETED_TODO: "COMPLETED_TODO",
    EDITETODO_TITLE: "EDITETODO_TITLE",
    MARKAS_ALL_CHECKED: "MARKAS_ALL_CHECKED"
}